/**
 * Lithium battery page: the air rules per battery type and the page text in
 * English and Dutch. Rules follow the IATA Dangerous Goods Regulations, 67th
 * edition (2026), as summarised in the IATA Battery Guidance Document 2026
 * (classification flowcharts, prohibitions, state of charge, marks, FAQ).
 * Company facts come from Express Cargo's own answers (October 2026).
 */

/**
 * One row per battery type, configuration and size.
 * pax/cao: net battery weight per package on passenger / cargo aircraft (null = forbidden)
 * pkg: unspec | rigid-stack | drop | equip   marks: class9 | cao | mark | mark-ex   docs: dgd | awb
 * soc: alone | with-1 | with-2 | in | none
 */
export const RULES = [
  { chem: 'ion', pack: 'alone', size: 'small', un: 'UN3480', pi: '965', section: 'IB', pax: null, cao: '10 kg', pkg: 'rigid-stack', marks: ['class9', 'cao', 'mark'], docs: 'dgd', soc: 'alone' },
  { chem: 'ion', pack: 'alone', size: 'large', un: 'UN3480', pi: '965', section: 'IA', pax: null, cao: '35 kg', pkg: 'unspec', marks: ['class9', 'cao'], docs: 'dgd', soc: 'alone' },
  { chem: 'ion', pack: 'with', size: 'small', un: 'UN3481', pi: '966', section: 'II', pax: '5 kg', cao: '5 kg', pkg: 'drop', marks: ['mark'], docs: 'awb', soc: 'with-2' },
  { chem: 'ion', pack: 'with', size: 'large', un: 'UN3481', pi: '966', section: 'I', pax: '5 kg', cao: '35 kg', pkg: 'unspec', marks: ['class9'], docs: 'dgd', soc: 'with-1' },
  { chem: 'ion', pack: 'in', size: 'small', un: 'UN3481', pi: '967', section: 'II', pax: '5 kg', cao: '5 kg', pkg: 'equip', marks: ['mark-ex'], docs: 'awb', soc: 'in' },
  { chem: 'ion', pack: 'in', size: 'large', un: 'UN3481', pi: '967', section: 'I', pax: '5 kg', cao: '35 kg', pkg: 'equip', marks: ['class9'], docs: 'dgd', soc: 'in' },
  { chem: 'metal', pack: 'alone', size: 'small', un: 'UN3090', pi: '968', section: 'IB', pax: null, cao: '2.5 kg', pkg: 'rigid-stack', marks: ['class9', 'cao', 'mark'], docs: 'dgd', soc: 'none' },
  { chem: 'metal', pack: 'alone', size: 'large', un: 'UN3090', pi: '968', section: 'IA', pax: null, cao: '35 kg', pkg: 'unspec', marks: ['class9', 'cao'], docs: 'dgd', soc: 'none' },
  { chem: 'metal', pack: 'with', size: 'small', un: 'UN3091', pi: '969', section: 'II', pax: '5 kg', cao: '5 kg', pkg: 'drop', marks: ['mark'], docs: 'awb', soc: 'none' },
  { chem: 'metal', pack: 'with', size: 'large', un: 'UN3091', pi: '969', section: 'I', pax: '5 kg', cao: '35 kg', pkg: 'unspec', marks: ['class9'], docs: 'dgd', soc: 'none' },
  { chem: 'metal', pack: 'in', size: 'small', un: 'UN3091', pi: '970', section: 'II', pax: '5 kg', cao: '5 kg', pkg: 'equip', marks: ['mark-ex'], docs: 'awb', soc: 'none' },
  { chem: 'metal', pack: 'in', size: 'large', un: 'UN3091', pi: '970', section: 'I', pax: '5 kg', cao: '35 kg', pkg: 'equip', marks: ['class9'], docs: 'dgd', soc: 'none' },
];

/** official proper shipping names (English on air documents in every language) */
export const PSN = {
  'ion-alone': 'Lithium ion batteries',
  'ion-with': 'Lithium ion batteries packed with equipment',
  'ion-in': 'Lithium ion batteries contained in equipment',
  'metal-alone': 'Lithium metal batteries',
  'metal-with': 'Lithium metal batteries packed with equipment',
  'metal-in': 'Lithium metal batteries contained in equipment',
};

export const lithium = {
  en: {
    title: 'Lithium battery shipping, UN3480 & UN3481 | Air, road, sea | Express Cargo',
    description:
      'Lithium battery shipping from Schiphol: UN3480 and UN3481, on their own, packed with or inside equipment. By air, road and sea, IATA DGR certified, with a focus on medical equipment.',
    nav: 'Lithium batteries',
    code: 'UN3480 · UN3481 · CLASS 9',
    h1: 'Lithium batteries, shipped right the first time.',
    lede: 'On their own, packed with equipment or built into it: by air, road or sea. Our IATA DGR-certified team classifies, packs, marks and documents every shipment, with a strong focus on medical equipment and healthcare.',
    quote: 'Quote a lithium shipment',
    chips: ['IATA member', 'IATA DGR certified', 'Air · road · sea', 'At Schiphol since 2002'],
    art: {
      class9: 'Class 9 lithium battery label',
      mark: 'Lithium battery mark',
      cao: 'Cargo Aircraft Only',
      stateA: 'UN3480 · on their own · cargo aircraft only',
      stateB: 'UN3481 · inside equipment · Section II',
      title: 'A package of lithium batteries with its labels: the Class 9 lithium battery label, the lithium battery mark and the Cargo Aircraft Only label',
    },
    rules: {
      title: 'Four rules that catch shippers out.',
      items: [
        ['30%', 'Maximum state of charge for lithium-ion batteries shipped on their own (UN3480), and since 1 January 2026 also for batteries packed with equipment.'],
        ['0 kg', 'Lithium batteries shipped on their own (UN3480, UN3090) are forbidden on passenger aircraft: they fly on cargo aircraft only.'],
        ['5 kg', 'Maximum net weight of lithium batteries per package on a passenger aircraft, when they are packed with or inside equipment.'],
        ['38.3', 'Every cell and battery type must pass the UN 38.3 tests, and the manufacturer makes the test summary available.'],
      ],
      source: 'Source: IATA Dangerous Goods Regulations, 67th edition (2026), and the IATA Battery Guidance Document 2026.',
    },
    cls: {
      kicker: 'Battery classifier',
      title: 'Which rules apply to your batteries?',
      lede: 'Three questions, and you see the UN number, packing instruction, aircraft, marks and documents for air transport.',
      legend: { chem: 'Battery type', pack: 'How do they travel?', size: 'Size' },
      opt: {
        ion: ['Lithium-ion', 'rechargeable, incl. Li-polymer'],
        metal: ['Lithium metal', 'mostly non-rechargeable'],
        alone: ['On their own', 'power banks too'],
        with: ['Packed with equipment', 'spares in the same box'],
        in: ['Inside equipment', 'built into the device'],
        'small-ion': ['Up to 100 Wh', 'cells up to 20 Wh'],
        'large-ion': ['Over 100 Wh', 'or cells over 20 Wh'],
        'small-metal': ['Up to 2 g lithium', 'cells up to 1 g'],
        'large-metal': ['Over 2 g lithium', 'or cells over 1 g'],
      },
      f: { un: 'UN number', pi: 'Packing instruction', aircraft: 'Aircraft', limit: 'Per package', pkg: 'Packaging', marks: 'Marks & labels', docs: 'Documents', soc: 'State of charge' },
      section: 'Section',
      aircraft: { cao: 'Cargo aircraft only', both: 'Passenger or cargo aircraft' },
      limit: {
        cao: (k) => `Forbidden on passenger aircraft; up to ${k} of batteries per package on cargo aircraft`,
        same: (k) => `Up to ${k} of batteries per package, passenger and cargo aircraft`,
        both: (p, c) => `Up to ${p} of batteries per package on passenger aircraft, ${c} on cargo aircraft`,
      },
      pkg: {
        unspec: 'UN-specification packaging (Packing Group II performance)',
        'rigid-stack': 'Strong rigid outer packaging able to withstand a 3 m stack test; no UN-specification packaging needed',
        drop: 'Strong rigid packaging able to withstand a 1.2 m drop test',
        equip: 'Strong rigid outer packaging, unless the equipment itself protects the battery; secured against switching on by accident',
      },
      marks: {
        class9: 'Class 9 lithium battery hazard label',
        cao: 'Cargo Aircraft Only label',
        mark: 'Lithium battery mark',
        'mark-ex': 'Lithium battery mark (not needed for up to 4 cells or 2 batteries installed per package, at most 2 packages per consignment)',
      },
      docs: {
        dgd: 'Shipper’s Declaration for Dangerous Goods',
        awb: 'No Shipper’s Declaration; a Section II statement on the air waybill when the package carries the battery mark',
        test: 'UN 38.3 test summary available from the manufacturer',
      },
      soc: {
        alone: 'At most 30% of rated capacity (mandatory)',
        'with-1': 'At most 30% of rated capacity, mandatory since 1 January 2026',
        'with-2': 'At most 30% for batteries above 2.7 Wh, mandatory since 1 January 2026',
        in: '30% (or 25% indicated capacity) strongly recommended, not mandatory',
        none: 'No state-of-charge limit for lithium metal',
      },
      what: {
        'ion-alone': 'lithium-ion batteries',
        'ion-with': 'lithium-ion batteries packed with equipment',
        'ion-in': 'equipment with lithium-ion batteries',
        'metal-alone': 'lithium metal batteries',
        'metal-with': 'lithium metal batteries packed with equipment',
        'metal-in': 'equipment with lithium metal batteries',
      },
      batteries: { ion: 'Lithium-ion', metal: 'Lithium metal', alone: 'on their own', with: 'packed with equipment', in: 'inside equipment' },
      disclaimer: 'A guide to the IATA rules for air transport, not a classification. We confirm every shipment before it is booked.',
      quote: 'Quote this shipment',
      table: 'All twelve combinations in one table',
      th: ['Your batteries', 'UN number', 'Packing instruction', 'Aircraft', 'Packaging', 'Marks & labels', 'Documents', 'State of charge'],
      live: (un, pi, section, aircraft) => `${un}, packing instruction ${pi} Section ${section}: ${aircraft}.`,
    },
    journey: {
      title: 'How we prepare a lithium shipment.',
      steps: (n) => `${n} steps · one coordinator`,
      step: 'Step',
      items: [
        ['search-check', 'CHECK', 'Classification', 'We confirm the UN number, packing instruction and section from your battery data: chemistry, watt-hours or lithium content, and how the batteries travel.', ['Lithium-ion or lithium metal', 'Watt-hours or lithium content per cell and battery', 'On their own, packed with or inside equipment']],
        ['clipboard-check', 'TEST', 'Test summary & charge', 'Every cell and battery type must have passed the UN 38.3 tests. We check the test summary and, for lithium-ion, the state of charge wherever the rules set a limit.', ['UN 38.3 test summary from the manufacturer', 'State of charge at or below 30% where required', 'No damaged or defective batteries']],
        ['package', 'PACK', 'Packing & marks', 'We arrange UN-specification packaging where it is required, and can pack and prepare the shipment ourselves, with the right marks and labels.', ['UN-specification packaging arranged', 'Terminals protected against short circuit', 'Class 9 label, battery mark and Cargo Aircraft Only label as required']],
        ['file-text', 'DOCS', 'Documents', 'The Shipper’s Declaration for Dangerous Goods, or the Section II statement on the air waybill, plus the customs documents.', ['Shipper’s Declaration for Section I shipments', 'Section II statement on the air waybill', 'Export and import customs documents']],
        ['plane', 'BOOK', 'Booking & delivery', 'Booked with a carrier that accepts the batteries, on a cargo aircraft when the rules require it, or by road or sea when that suits better. Delivered door to door.', ['Carrier acceptance confirmed before booking', 'Cargo aircraft when the batteries require it', 'One coordinator from pickup to delivery']],
      ],
      plates: {
        example: 'EXAMPLE',
        wh: 'Wh = V × Ah',
        battery: 'Li-ion battery pack',
        within: 'Within 100 Wh, cells within 20 Wh',
        tags: ['Lithium-ion', 'Inside equipment', 'UN3481 · PI 967'],
        summary: 'UN 38.3 TEST SUMMARY',
        tests: ['T.1 Altitude simulation', 'T.2 Thermal test', 'T.3 Vibration', 'T.4 Shock', 'T.5 External short circuit', 'T.6 Impact / crush', 'T.7 Overcharge', 'T.8 Forced discharge'],
        pass: 'PASS',
        soc: 'State of charge',
        pkgTitle: 'PI 966 · SECTION I',
        pkgLines: ['UN3481', 'Lithium ion batteries', 'packed with equipment', 'Net qty 4.2 kg'],
        pkgNotes: ['UN-specification packaging', 'Class 9 lithium battery label', 'Terminals protected'],
        dgd: 'SHIPPER’S DECLARATION FOR DANGEROUS GOODS',
        dgdRow: ['UN3481', 'Lithium ion batteries packed with equipment', '9', 'PI 966'],
        sign: 'Signature',
        awb: 'AIR WAYBILL · HANDLING INFORMATION',
        awbLine: 'Lithium ion batteries in compliance with Section II of PI 967',
        cao: 'CARGO AIRCRAFT ONLY',
        modes: ['Air · IATA DGR', 'Road · ADR', 'Sea · IMDG'],
      },
    },
    need: {
      title: 'What we need from you.',
      lede: 'Send what you have. If something is missing, we tell you exactly what, and why.',
      items: [
        'Battery type: lithium-ion or lithium metal',
        'Watt-hours (lithium-ion) or lithium content in grams (lithium metal), per cell and per battery',
        'How they travel: on their own, packed with equipment or built in',
        'Number of batteries and net weight per package',
        'The UN 38.3 test summary from the manufacturer',
        'State of charge (lithium-ion), and confirmation that the batteries are not damaged or defective',
      ],
      cta: 'Send the details',
    },
    refuse: {
      kicker: 'Not accepted',
      title: 'Damaged or defective batteries.',
      text: 'We don’t accept damaged or defective lithium batteries, by any mode, even where a special approval might be possible. By air, batteries that are damaged or recalled for safety reasons are forbidden anyway (IATA Special Provision A154).',
    },
    medical: {
      kicker: 'Medical equipment & healthcare',
      title: 'Lithium inside medical equipment.',
      text: 'Monitors, pumps, portable scanners: much of today’s medical equipment runs on lithium-ion, often with a spare pack in the box. That is where our experience lies: medical equipment, healthcare, pharmaceuticals and other specialised cargo.',
      items: [
        'Equipment with batteries inside (UN3481, PI 967)',
        'Spare packs in the same box (PI 966, at 30% charge or less since 2026)',
        'Temperature data loggers travelling with pharma',
        'The complete process: air freight, road transport, customs clearance, documentation, special handling and time-critical delivery',
      ],
      alt: 'Gate of Madiany Sub County Hospital in Kenya, where Express Cargo delivered medical equipment',
      caption: 'Project · medical equipment to a hospital in Kenya',
    },
    modes: {
      title: 'By air, road and sea.',
      lede: 'Subject to the applicable regulations, carrier acceptance and the classification of the batteries.',
      items: [
        ['air-freight', 'Air freight', 'plane', 'air-loading', 'IATA Dangerous Goods Regulations. Cargo aircraft only for batteries on their own; passenger or cargo aircraft for batteries with or inside equipment.'],
        ['road-transport', 'Road transport', 'truck', 'road-highway', 'ADR, the European agreement on dangerous goods by road, across Europe and beyond.'],
        ['sea-freight', 'Sea freight', 'ship', 'sea-river', 'The IMDG Code for dangerous goods at sea, for larger volumes and long distances.'],
      ],
    },
    close: {
      title: 'Lithium batteries to move?',
      text: 'Send the battery type, the watt-hours and how they travel. A coordinator who knows the rules comes back to you fast.',
      email: 'Email us',
    },
    call: '+31 20 333 2405',
    skip: { cls: 'Battery classifier' },
  },

  nl: {
    title: 'Lithiumbatterijen verzenden, UN3480 & UN3481 | Lucht, weg, zee | Express Cargo',
    description:
      'Lithiumbatterijen verzenden vanaf Schiphol: UN3480 en UN3481, los, bij of in apparatuur. Door de lucht, over de weg en over zee, IATA DGR-gecertificeerd, met focus op medische apparatuur.',
    nav: 'Lithiumbatterijen',
    code: 'UN3480 · UN3481 · KLASSE 9',
    h1: 'Lithiumbatterijen, in één keer goed verzonden.',
    lede: 'Los, verpakt bij apparatuur of erin ingebouwd: door de lucht, over de weg of over zee. Ons IATA DGR-gecertificeerde team classificeert, verpakt, markeert en documenteert elke zending, met een sterke focus op medische apparatuur en de zorg.',
    quote: 'Offerte voor lithiumbatterijen',
    chips: ['IATA-lid', 'IATA DGR-gecertificeerd', 'Lucht · weg · zee', 'Sinds 2002 op Schiphol'],
    art: {
      class9: 'Gevarenetiket klasse 9',
      mark: 'Lithiumbatterijmarkering',
      cao: 'Cargo Aircraft Only',
      stateA: 'UN3480 · los · alleen vrachtvliegtuig',
      stateB: 'UN3481 · in apparatuur · Section II',
      title: 'Een pakket lithiumbatterijen met de etiketten: het gevarenetiket klasse 9 voor lithiumbatterijen, de lithiumbatterijmarkering en het etiket Cargo Aircraft Only',
    },
    rules: {
      title: 'Vier regels waar verzenders op struikelen.',
      items: [
        ['30%', 'Maximale laadtoestand voor lithium-ionbatterijen die los worden verzonden (UN3480), en sinds 1 januari 2026 ook voor batterijen die bij apparatuur zijn verpakt.'],
        ['0 kg', 'Los verzonden lithiumbatterijen (UN3480, UN3090) zijn verboden in passagiersvliegtuigen: ze vliegen alleen met vrachtvliegtuigen.'],
        ['5 kg', 'Maximaal nettogewicht aan lithiumbatterijen per pakket in een passagiersvliegtuig, als ze bij of in apparatuur zitten.'],
        ['38.3', 'Elk cel- en batterijtype moet de UN 38.3-tests doorstaan, en de fabrikant stelt de testsamenvatting beschikbaar.'],
      ],
      source: 'Bron: IATA Dangerous Goods Regulations, 67e editie (2026), en het IATA Battery Guidance Document 2026.',
    },
    cls: {
      kicker: 'Batterijwijzer',
      title: 'Welke regels gelden voor uw batterijen?',
      lede: 'Drie vragen, en u ziet het UN-nummer, de verpakkingsinstructie, het vliegtuig, de markeringen en de documenten voor luchtvervoer.',
      legend: { chem: 'Type batterij', pack: 'Hoe reizen ze?', size: 'Grootte' },
      opt: {
        ion: ['Lithium-ion', 'oplaadbaar, ook Li-polymeer'],
        metal: ['Lithiummetaal', 'meestal niet oplaadbaar'],
        alone: ['Los', 'ook powerbanks'],
        with: ['Bij apparatuur', 'reserve in dezelfde doos'],
        in: ['In apparatuur', 'ingebouwd in het apparaat'],
        'small-ion': ['Tot 100 Wh', 'cellen tot 20 Wh'],
        'large-ion': ['Boven 100 Wh', 'of cellen boven 20 Wh'],
        'small-metal': ['Tot 2 g lithium', 'cellen tot 1 g'],
        'large-metal': ['Boven 2 g lithium', 'of cellen boven 1 g'],
      },
      f: { un: 'UN-nummer', pi: 'Verpakkingsinstructie', aircraft: 'Vliegtuig', limit: 'Per pakket', pkg: 'Verpakking', marks: 'Markeringen & etiketten', docs: 'Documenten', soc: 'Laadtoestand' },
      section: 'Section',
      aircraft: { cao: 'Alleen vrachtvliegtuig', both: 'Passagiers- of vrachtvliegtuig' },
      limit: {
        cao: (k) => `Verboden in passagiersvliegtuigen; tot ${k.replace('.', ',')} batterijen per pakket in vrachtvliegtuigen`,
        same: (k) => `Tot ${k} batterijen per pakket, in passagiers- en vrachtvliegtuigen`,
        both: (p, c) => `Tot ${p} batterijen per pakket in passagiersvliegtuigen, ${c} in vrachtvliegtuigen`,
      },
      pkg: {
        unspec: 'UN-gecertificeerde verpakking (prestatieniveau verpakkingsgroep II)',
        'rigid-stack': 'Stevige, stijve buitenverpakking die een stapeltest van 3 m doorstaat; geen UN-verpakking nodig',
        drop: 'Stevige, stijve verpakking die een valtest van 1,2 m doorstaat',
        equip: 'Stevige, stijve buitenverpakking, tenzij het apparaat zelf de batterij beschermt; beveiligd tegen per ongeluk inschakelen',
      },
      marks: {
        class9: 'Gevarenetiket klasse 9 voor lithiumbatterijen',
        cao: 'Etiket Cargo Aircraft Only',
        mark: 'Lithiumbatterijmarkering',
        'mark-ex': 'Lithiumbatterijmarkering (niet nodig bij maximaal 4 cellen of 2 ingebouwde batterijen per pakket, tot 2 pakketten per zending)',
      },
      docs: {
        dgd: 'Shipper’s Declaration for Dangerous Goods',
        awb: 'Geen Shipper’s Declaration; een Section II-verklaring op de air waybill als het pakket de batterijmarkering draagt',
        test: 'UN 38.3-testsamenvatting beschikbaar bij de fabrikant',
      },
      soc: {
        alone: 'Maximaal 30% van de nominale capaciteit (verplicht)',
        'with-1': 'Maximaal 30% van de nominale capaciteit, verplicht sinds 1 januari 2026',
        'with-2': 'Maximaal 30% voor batterijen boven 2,7 Wh, verplicht sinds 1 januari 2026',
        in: '30% (of 25% weergegeven capaciteit) sterk aanbevolen, niet verplicht',
        none: 'Geen limiet voor de laadtoestand bij lithiummetaal',
      },
      what: {
        'ion-alone': 'lithium-ionbatterijen, los',
        'ion-with': 'lithium-ionbatterijen bij apparatuur',
        'ion-in': 'apparatuur met lithium-ionbatterijen',
        'metal-alone': 'lithiummetaalbatterijen, los',
        'metal-with': 'lithiummetaalbatterijen bij apparatuur',
        'metal-in': 'apparatuur met lithiummetaalbatterijen',
      },
      batteries: { ion: 'Lithium-ion', metal: 'Lithiummetaal', alone: 'los', with: 'verpakt bij apparatuur', in: 'in apparatuur' },
      disclaimer: 'Een wegwijzer door de IATA-regels voor luchtvervoer, geen classificatie. Wij controleren elke zending voordat die wordt geboekt.',
      quote: 'Offerte voor deze zending',
      table: 'Alle twaalf combinaties in één tabel',
      th: ['Uw batterijen', 'UN-nummer', 'Verpakkingsinstructie', 'Vliegtuig', 'Verpakking', 'Markeringen & etiketten', 'Documenten', 'Laadtoestand'],
      live: (un, pi, section, aircraft) => `${un}, verpakkingsinstructie ${pi} Section ${section}: ${aircraft.toLowerCase()}.`,
    },
    journey: {
      title: 'Zo bereiden wij een lithiumzending voor.',
      steps: (n) => `${n} stappen · één coördinator`,
      step: 'Stap',
      items: [
        ['CHECK', 'Classificatie', 'We bevestigen UN-nummer, verpakkingsinstructie en section op basis van uw batterijgegevens: het type, de wattuur of het lithiumgehalte, en hoe de batterijen reizen.', ['Lithium-ion of lithiummetaal', 'Wattuur of lithiumgehalte per cel en batterij', 'Los, bij of in apparatuur']],
        ['TEST', 'Testsamenvatting & laadtoestand', 'Elk cel- en batterijtype moet de UN 38.3-tests hebben doorstaan. We controleren de testsamenvatting en, bij lithium-ion, de laadtoestand waar de regels een limiet stellen.', ['UN 38.3-testsamenvatting van de fabrikant', 'Laadtoestand maximaal 30% waar dat verplicht is', 'Geen beschadigde of defecte batterijen']],
        ['VERPAK', 'Verpakken & markeren', 'We regelen UN-gecertificeerde verpakking waar die nodig is, en kunnen de zending zelf verpakken en voorbereiden, met de juiste markeringen en etiketten.', ['UN-gecertificeerde verpakking geregeld', 'Polen beschermd tegen kortsluiting', 'Etiket klasse 9, batterijmarkering en Cargo Aircraft Only waar nodig']],
        ['DOCS', 'Documenten', 'De Shipper’s Declaration for Dangerous Goods, of de Section II-verklaring op de air waybill, plus de douanedocumenten.', ['Shipper’s Declaration voor Section I-zendingen', 'Section II-verklaring op de air waybill', 'Export- en importdocumenten voor de douane']],
        ['BOEK', 'Boeken & afleveren', 'Geboekt bij een vervoerder die de batterijen accepteert, met een vrachtvliegtuig als de regels dat eisen, of over de weg of zee als dat beter past. Van deur tot deur afgeleverd.', ['Acceptatie door de vervoerder vooraf bevestigd', 'Vrachtvliegtuig als de batterijen dat vereisen', 'Eén coördinator van ophalen tot aflevering']],
      ],
      plates: {
        example: 'VOORBEELD',
        wh: 'Wh = V × Ah',
        battery: 'Li-ion-batterijpakket',
        within: 'Binnen 100 Wh, cellen binnen 20 Wh',
        tags: ['Lithium-ion', 'In apparatuur', 'UN3481 · PI 967'],
        summary: 'UN 38.3-TESTSAMENVATTING',
        tests: ['T.1 Hoogtesimulatie', 'T.2 Thermische test', 'T.3 Trillingen', 'T.4 Schokken', 'T.5 Externe kortsluiting', 'T.6 Impact / verbrijzeling', 'T.7 Overladen', 'T.8 Geforceerde ontlading'],
        pass: 'OK',
        soc: 'Laadtoestand',
        pkgTitle: 'PI 966 · SECTION I',
        pkgLines: ['UN3481', 'Lithium ion batteries', 'packed with equipment', 'Netto 4,2 kg'],
        pkgNotes: ['UN-gecertificeerde verpakking', 'Gevarenetiket klasse 9', 'Polen beschermd'],
        dgd: 'SHIPPER’S DECLARATION FOR DANGEROUS GOODS',
        dgdRow: ['UN3481', 'Lithium ion batteries packed with equipment', '9', 'PI 966'],
        sign: 'Handtekening',
        awb: 'AIR WAYBILL · HANDLING INFORMATION',
        awbLine: 'Lithium ion batteries in compliance with Section II of PI 967',
        cao: 'CARGO AIRCRAFT ONLY',
        modes: ['Lucht · IATA DGR', 'Weg · ADR', 'Zee · IMDG'],
      },
    },
    need: {
      title: 'Wat we van u nodig hebben.',
      lede: 'Stuur wat u heeft. Ontbreekt er iets, dan zeggen we precies wat, en waarom.',
      items: [
        'Type batterij: lithium-ion of lithiummetaal',
        'Wattuur (lithium-ion) of lithiumgehalte in gram (lithiummetaal), per cel en per batterij',
        'Hoe ze reizen: los, verpakt bij apparatuur of ingebouwd',
        'Aantal batterijen en nettogewicht per pakket',
        'De UN 38.3-testsamenvatting van de fabrikant',
        'De laadtoestand (lithium-ion), en de bevestiging dat de batterijen niet beschadigd of defect zijn',
      ],
      cta: 'Gegevens sturen',
    },
    refuse: {
      kicker: 'Niet geaccepteerd',
      title: 'Beschadigde of defecte batterijen.',
      text: 'Beschadigde of defecte lithiumbatterijen accepteren wij niet, met geen enkele vervoerswijze, ook niet als een speciale ontheffing mogelijk zou zijn. Door de lucht zijn batterijen die beschadigd zijn of om veiligheidsredenen zijn teruggeroepen sowieso verboden (IATA Special Provision A154).',
    },
    medical: {
      kicker: 'Medische apparatuur & zorg',
      title: 'Lithium in medische apparatuur.',
      text: 'Monitoren, pompen, draagbare scanners: veel medische apparatuur werkt op lithium-ion, vaak met een reservebatterij in de doos. Daar ligt onze ervaring: medische apparatuur, de zorg, farmaceutica en andere gespecialiseerde lading.',
      items: [
        'Apparatuur met ingebouwde batterijen (UN3481, PI 967)',
        'Reservebatterijen in dezelfde doos (PI 966, sinds 2026 maximaal 30% geladen)',
        'Temperatuurloggers die met farma meereizen',
        'Het hele proces: luchtvracht, wegtransport, inklaring, documentatie, speciale behandeling en spoedlevering',
      ],
      alt: 'Toegangspoort van het Madiany Sub County Hospital in Kenia, waar Express Cargo medische apparatuur afleverde',
      caption: 'Project · medische apparatuur voor een ziekenhuis in Kenia',
    },
    modes: {
      title: 'Door de lucht, over de weg en over zee.',
      lede: 'Afhankelijk van de geldende regels, acceptatie door de vervoerder en de classificatie van de batterijen.',
      items: [
        ['luchtvracht', 'Luchtvracht', 'IATA Dangerous Goods Regulations. Alleen vrachtvliegtuig voor losse batterijen; passagiers- of vrachtvliegtuig voor batterijen bij of in apparatuur.'],
        ['wegtransport', 'Wegtransport', 'ADR, het Europese verdrag voor gevaarlijke stoffen over de weg, in heel Europa en daarbuiten.'],
        ['zeevracht', 'Zeevracht', 'De IMDG-code voor gevaarlijke stoffen over zee, voor grotere volumes en lange afstanden.'],
      ],
    },
    close: {
      title: 'Lithiumbatterijen te verzenden?',
      text: 'Stuur het type batterij, het aantal wattuur en hoe ze reizen. Een coördinator die de regels kent, komt snel bij u terug.',
      email: 'Mail ons',
    },
    call: '+31 20 333 2405',
    skip: { cls: 'Batterijwijzer' },
  },
};
