/**
 * Dutch text for the service pages, keyed by the English slug. Structure
 * mirrors scripts/services.mjs; icons, photos and videos come from there.
 * Wording follows www.express-cargo.nl where the original says it.
 */
export const servicesNl = {
  'air-freight': {
    nlSlug: 'luchtvracht',
    nav: 'Luchtvracht',
    code: 'LUCHT · AMS → WERELDWIJD',
    title: 'Luchtvracht vanaf Schiphol | IATA DGR-gecertificeerd | Express Cargo',
    description:
      'Import- en exportluchtvracht vanaf Amsterdam Schiphol: gevaarlijke stoffen, lithiumbatterijen, biologische en farmaceutische zendingen, temperatuurbeheersing, douaneformaliteiten en douane-entrepot. IATA-geregistreerd en IATA DGR-gecertificeerd.',
    h1: 'Luchtvracht, van deur tot deur.',
    lede: 'Verzenden per vliegtuig is wereldwijd de snelste manier van transport: binnen enkele dagen kan uw zending aan de andere kant van de wereld staan. Express Cargo is IATA-geregistreerd en IATA DGR-gecertificeerd.',
    journeyTitle: 'Zo reist een luchtvrachtzending.',
    journey: [
      ['OPHALEN', 'Ophalen', 'We halen op aan uw deur, of bij uw leverancier, waar ook ter wereld in ons netwerk van lokale agenten.'],
      ['DOCS', 'Documenten & DGR-check', 'Exportaangifte gedaan, gevaarlijke stoffen aangemeld en verpakt volgens IATA DGR. Alle documenten op orde voordat de lading vertrekt.'],
      ['AMS', 'Vertrek vanaf Schiphol', 'Geboekt op de vlucht die past bij de lading en de deadline, opgebouwd en geladen.'],
      ['AANK', 'Aankomst & inklaring', 'Onze agent op de bestemming regelt de importformaliteiten, zodat de zending niet in een loods blijft staan.'],
      ['POD', 'Afgeleverd', 'Getekend voor ontvangst aan de deur. U krijgt het afleverbewijs, en één coördinator beantwoordde onderweg al uw vragen.'],
    ],
    facts: [
      ['Ophalen aan uw deur of bij uw leverancier', 'Verpakt en gelabeld voor de route', 'Ophaling bevestigd door uw coördinator'],
      ['Air waybill en handelsfactuur', 'Shipper’s Declaration for Dangerous Goods waar nodig', 'Exportaangifte ingediend bij de douane'],
      ['Geboekt op de vlucht die past bij lading en deadline', 'Opgebouwd en geladen op Schiphol', 'Vluchtgegevens naar u gestuurd'],
      ['Ontvangen door onze agent op de bestemming', 'Inklaring en invoerrechten geregeld', 'Temperatuur- en DG-eisen opnieuw gecontroleerd'],
      ['Afgeleverd op het opgegeven adres', 'Afleverbewijs met u gedeeld', 'Eén coördinator van begin tot eind'],
    ],
    capsTitle: 'Wat we vliegen.',
    capsLede: 'Zendingen die meer vragen dan een boeking: de juiste verpakking, de juiste papieren en iemand die opvolgt.',
    caps: [
      ['Gevaarlijke stoffen', 'Aangemeld, verpakt en gelabeld volgens IATA DGR door gecertificeerde medewerkers.'],
      ['Lithiumbatterijen', 'UN3480, UN3481 en UN3090/3091, los of in apparatuur.'],
      ['Biologisch & farmaceutisch', 'Klinische samples, UN3373-specimens en farma, op droogijs waar nodig.'],
      ['Temperatuurgecontroleerd', '+2–8 °C, +15–25 °C en diepgevroren, van verpakking tot actieve containers.'],
      ['Douanedocumenten', 'Export- en importformaliteiten geregeld, documenten opgesteld en gecontroleerd.'],
      ['Douane-entrepot', 'Opslag onder douanetoezicht op Schiphol tot de goederen verder gaan.'],
    ],
    quote: 'Snelheid, communicatie en service staan bij ons hoog in het vaandel.',
    mediaAlt: 'Een vrachtvliegtuig op de startbaan',
    stats: [['IATA', 'geregistreerd agent'], ['DGR', 'gecertificeerde medewerkers'], ['2002', 'op Schiphol sinds']],
    tool: 'Luchtvracht wordt berekend op volume of gewicht, wat het hoogst is. Reken het uit voordat u een offerte vraagt.',
  },
  'sea-freight': {
    nlSlug: 'zeevracht',
    nav: 'Zeevracht',
    code: 'ZEE · RTM → WERELDWIJD',
    title: 'Zeevracht FCL & LCL | Wereldwijd transport over zee | Express Cargo',
    description:
      'Wereldwijde zeevracht met Express Cargo: volle containers (FCL) en deelladingen (LCL) met onze partners, alle documenten geregeld, persoonlijke service vanaf Schiphol.',
    h1: 'Zeevracht, vol of gedeeld.',
    lede: 'Overal ter wereld zendingen halen of leveren, ook via het water. Volle containers (FCL) of kleinere zendingen die samen met andere in één container gaan (LCL), met alle documenten voor u geregeld.',
    journeyTitle: 'Zo reist een zeevrachtzending.',
    journey: [
      ['OPHALEN', 'Ophalen', 'Opgehaald bij de leverancier, met een dieplader als het moet, en naar de haven gebracht.'],
      ['LADEN', 'De container in', 'Uw eigen container (FCL), of samen met andere lading in één container (LCL). Verzegeld, vastgezet, gedocumenteerd.'],
      ['POL', 'Haven van vertrek', 'Exportaangifte gedaan en geladen bij de rederij die past bij route en datum.'],
      ['ZEE', 'Op zee', 'We volgen het schip en laten het u weten als er iets verandert, niet achteraf.'],
      ['POD', 'Van haven tot deur', 'Onze partner op de bestemming klaart de lading in en levert af aan uw deur.'],
    ],
    facts: [
      ['Opgehaald bij de leverancier', 'Dieplader voor zware of oversized lading', 'Naar de haven of het consolidatiemagazijn gebracht'],
      ['FCL: uw eigen 20′, 40′ of 40′ high cube', 'LCL: samen met andere lading', 'Verzegeld, vastgezet en gedocumenteerd'],
      ['Exportaangifte gedaan', 'Cognossement (bill of lading) uitgegeven', 'Geladen bij de rederij die past bij route en datum'],
      ['Het schip de hele reis gevolgd', 'Wijzigingen direct gemeld', 'Aankomstbericht voorbereid'],
      ['Inklaring op de bestemming', 'Container afgeleverd of gelost', 'Afgeleverd aan uw deur'],
    ],
    capsTitle: 'Wat we verschepen.',
    capsLede: 'Ook bij zeevracht staat persoonlijke service hoog op de lijst, en we verzorgen alle documenten voor u.',
    caps: [
      ['Volle container (FCL)', '20′, 40′ en 40′ high cube, van deur tot deur.'],
      ['Deellading (LCL)', 'Betaal voor de ruimte die u gebruikt, samen met andere lading.'],
      ['Flatracks & out of gauge', 'Voertuigen en machines op 40′ high-cube flatracks.'],
      ['Alle documenten', 'Cognossementen, douane en certificaten voor u opgesteld.'],
      ['Betrouwbare partners', 'Expediteurs en agenten met wie we al jaren werken.'],
      ['Eén coördinator', 'Iemand die uw zending kent, van boeking tot aflevering.'],
    ],
    quote: 'Twee trucks, twee 40′-flatracks, één zending naar Brunei. Samen hebben we het geflikt.',
    mediaAlt: 'Twee trucks vastgezet op flatrackcontainers voor verscheping naar Brunei',
    stats: [['FCL', 'volle containers'], ['LCL', 'deelladingen'], ['RTM', 'via Rotterdam']],
    tool: 'LCL wordt berekend per vrachtton: kubieke meters of tonnen, wat het hoogst is.',
  },
  'road-transport': {
    nlSlug: 'wegtransport',
    nav: 'Wegtransport',
    code: 'WEG · EUROPA & VERDER',
    title: 'Wegtransport Europa | Groupage, dedicated, TAPA TSR1 | Express Cargo',
    description:
      'Nationaal en internationaal wegtransport met Express Cargo: van 1 tot 10.000 kg en van 1 tot 200 pallets. Dedicated transport, white glove, TAPA TSR1, kunst, hangende kleding, groupage en medische samples.',
    h1: 'Wegtransport, van één doos tot een volle trailer.',
    lede: 'Nationaal en internationaal wegtransport, of uw zending nu 1 of 10.000 kg weegt, naar de meest uiteenlopende bestemmingen in Europa en daarbuiten. Eén pallet of 200: voor elke bestemming hebben we een specialist in ons netwerk.',
    journeyTitle: 'Zo reist een wegtransport.',
    journey: [
      ['BOEKEN', 'Boeking', 'Groupage of dedicated, met of zonder beveiliger: we kiezen de juiste oplossing voor de lading.'],
      ['OPHALEN', 'Ophalen', 'Geladen aan uw dock in het afgesproken tijdslot, gecontroleerd en vastgezet.'],
      ['ONDERWEG', 'Onderweg', 'Direct met een dedicated voertuig, of via het groupagenetwerk van onze vaste partners.'],
      ['TRACK', 'Trackinglink', 'Waardevolle ladingen reizen met een trackinglink, zodat u ziet waar uw goederen zijn.'],
      ['POD', 'Afgeleverd', 'Veilig van A naar B, en getekend voor ontvangst aan de deur.'],
    ],
    facts: [
      ['Groupage of een dedicated voertuig', 'Beveiliger en TAPA TSR1 op aanvraag', 'Ophaalmoment met u afgesproken'],
      ['Geladen aan uw dock', 'Gecontroleerd en vastgezet', 'CMR-vrachtbrief'],
      ['Direct, of via een groupagehub', 'Rails voor hangende kleding, zorg voor kunst', 'Een gespecialiseerde partner per bestemming'],
      ['Trackinglink voor waardevolle ladingen', 'GPS in het voertuig', 'Updates van uw coördinator'],
      ['Getekend voor ontvangst aan de deur', 'White glove en binnenlevering op aanvraag', 'Afleverbewijs gedeeld'],
    ],
    capsTitle: 'Wat we rijden.',
    capsLede: 'Een selectie van wat we over de weg regelen, steeds met een partner met wie we al jaren werken.',
    caps: [
      ['Dedicated transport', 'Een voertuig alleen voor uw lading, direct naar het adres.'],
      ['White glove', 'Zorgvuldige behandeling, binnenlevering en installatie.'],
      ['TAPA TSR1', 'Het hoogste beveiligingsniveau voor waardevolle vracht.'],
      ['Kunsttransport', 'Klimaatbewust, zacht of in een kist verpakt, met zorg behandeld.'],
      ['Hangende kleding', 'Mode vervoerd aan rails, klaar voor de winkelvloer.'],
      ['Groupage', 'Gedeelde trailers voor 1 tot 200 pallets, netwerken van hoge kwaliteit.'],
      ['Medische samples', 'Klinische en labsamples over de weg, op tijd en binnen bereik.'],
    ],
    quote: 'Waardevolle goederen door Europa met een beveiliger en een trackinglink? Geen enkel probleem.',
    mediaAlt: 'Een vrachtwagen op de snelweg',
    stats: [['1–10.000', 'kilogram'], ['1–200', 'pallets'], ['TSR1', 'TAPA-beveiliging']],
    tool: 'Groupage wordt berekend op vloerruimte. Reken uw laadmeters uit.',
  },
  'special-projects': {
    nlSlug: 'projecten',
    nav: 'Projecten & white glove',
    code: 'PROJECTEN · WHITE GLOVE',
    title: 'Speciale projecten & white glove service | Express Cargo',
    description:
      'White glove levering, kisten op maat, Envirotainer-zendingen, oversized en waardevolle lading met Express Cargo: realtime tracking, binnenlevering en zo nodig een transportmanager mee.',
    h1: 'Projecten die niet in een formulier passen.',
    lede: 'Waardevolle, kwetsbare, grote of complexe zendingen: verpakt zoals u wilt, geïnspecteerd en gelabeld, en per koerier, luchtvracht of zeevracht naar elk land vervoerd, inclusief alle lokale afhandeling op de bestemming.',
    journeyTitle: 'Zo verloopt een project.',
    journey: [
      ['SURVEY', 'Inventarisatie', 'We kijken naar afmetingen, waarde, kwetsbaarheid, bederfelijkheid en de route voordat er iets wordt ingepakt.'],
      ['PACK', 'Verpakking op maat', 'Hard of zacht verpakt. Voor internationaal transport is een houten kist de gebruikelijke en aanbevolen keuze.'],
      ['MODE', 'De juiste modaliteit', 'Koerier, luchtvracht of zeevracht, samen met u gekozen op deadline en budget.'],
      ['ESCORT', 'Een manager mee', 'Indien nodig reist een transportmanager het hele traject met de zending mee.'],
      ['BINNEN', 'Binnenlevering', 'Getrainde mensen brengen het naar binnen en plaatsen het in de ruimte waar het hoort.'],
    ],
    facts: [
      ['Afmetingen, waarde en kwetsbaarheid', 'Bederfelijkheid en de route', 'Advies over verpakking en modaliteit'],
      ['Hard of zacht verpakt', 'Houten kisten voor internationaal transport', 'Gelabeld en geïnspecteerd'],
      ['Koerier, luchtvracht of zeevracht', 'Gekozen op deadline en budget', 'Lokale afhandeling op de bestemming geregeld'],
      ['Een transportmanager kan meereizen', 'Realtime tracking', 'Regelmatige updates tot de aflevering'],
      ['Naar binnen gebracht', 'In de juiste ruimte geplaatst', 'Gemonteerd waar nodig'],
    ],
    capsTitle: 'White glove, tot in detail.',
    capsLede: 'Oog voor detail zit in ons DNA: aandacht voor labels, inspectie vóór aflevering en zorgvuldige behandeling tijdens het hele proces.',
    caps: [
      ['Realtime tracking', 'GPS op de bezorgvoertuigen, statusupdates en locatie van de chauffeur.'],
      ['Verpakking op maat', 'Dikkere dozen, houten kisten, schuim: gekozen voor het object.'],
      ['Binnenlevering', 'Geplaatst in de juiste ruimte, gemonteerd waar nodig.'],
      ['Envirotainer', 'Actieve containers die farma op een constante temperatuur houden.'],
      ['Zwaar & oversized', 'Bouwmaterialen boven 3.000 kg, kisten van bijna 3 m lang.'],
      ['Premium service', 'Directe antwoorden en regelmatige updates tot het is afgeleverd.'],
    ],
    cases: [
      ['Mexico', 'Een kist van bijna drie meter lang en tweeënhalve meter hoog, helemaal naar Mexico gevlogen.', 'Lucht · kist op maat'],
      ['Australië', 'Twee Envirotainers vol farmaceutica, de hele reis op een constante temperatuur.', 'Lucht · actieve containers'],
      ['Brunei', 'Twee trucks met een waardevolle vacuümtank op twee 40′ high-cube flatracks.', 'Zee · out of gauge'],
      ['Perth', 'Bouwmaterialen boven 3.000 kg, opgehaald, verzegeld en onderweg naar Perth.', 'Lucht · zware lading'],
      ['South Uyoma, Kenia', 'Medische apparatuur afgeleverd bij het Madiany Sub County Hospital, een eerstelijnsziekenhuis van het ministerie van Volksgezondheid.', 'Lucht · afgelegen bestemming'],
      ['Europa', 'White glove levering: verpakt, geïnspecteerd, realtime gevolgd en binnen geplaatst.', 'Weg · white glove'],
    ],
    quote: 'Of het nu gaat om een sample op droogijs, een kwetsbaar kunstwerk of een (model)auto: wij regelen het.',
    mediaAlt: 'Een grote houten kist klaargemaakt voor luchtvracht naar Mexico',
    stats: [['3 m', 'kist naar Mexico'], ['3.000 kg+', 'naar Perth'], ['2', 'Envirotainers naar Australië']],
    tool: 'Wie betaalt wat, en waar gaat het risico over: het Incoterms® 2020-overzicht.',
  },
};
